### ISSUE TITLE
JSON format definition

### ISSUE THREAD

**Issue by wis3guy** [mulesoft-labs/api-console-cli#2]
Is the format of the JSON that is generated documented somewhere? Also, is the format specific to the API Console or a complete JSOn representation of the RAML document?

**Comment by jarrodek** [comment]
Hi,

Really sorry for late response. For some reason I had notifications turned off for this repo.

On a basic level this is JSON output from the RAML JavaScript parser. Then it is processed by my fork of the `raml2obj` library that makes output more consistent. Also, internally this library uses out expansion library to expand types.

I tried to document how the properties changes here:
- https://github.com/advanced-rest-client/raml-json-enhance#affected-properties

The library that performs transformation is here: https://github.com/advanced-rest-client/raml2obj
Though, it's not yet very well documented. This library (node module, but can be run in a browser) is used by all tools that generates JSON object for the console.

**Comment by jarrodek** [comment]
Closing as resolved
