### ISSUE TITLE
Incorrect type name for nested models

### ISSUE THREAD

**Issue by wis3guy** [mulesoft-labs/api-console-cli#3]
When i generate one of my own RAML files into JSON, i notice that all properties of nested models are copied into the response format description, without a reference to the original model. The type of the nested models is always `object` rather than the actual model name.

Suppose i have:

~~~
SearchResult
   criteria: SearchCriteria
   results: Item[]
~~~

Then in the JSON i see the model definitions at the bottom, but a resource that returns the `SearchResult` model has all of the properties of `SearchCriteria` and `Item` _incorporated_ without and are marked as `object`.

Make sense?

**Comment by jarrodek** [comment]
If I understand correctly,

On a resource level (in JSON output) the type describes an object that have combined properties from both `criteria` and `results`?

**Comment by jarrodek** [comment]
Closing for the lack of response.
