### ISSUE TITLE
Allow anonymous usage statistics to help improve our CLI tools?

### ISSUE THREAD

**Issue by shaburov** [mulesoft-labs/api-console-cli#32]
Docker build 
```
Step 10/11 : RUN api-console build -n -t v4.1.0 --json api.raml
 ---> Running in b802f7bd71ed
? Allow anonymous usage statistics to help improve our CLI tools? (Y/n) The command '/bin/sh -c api-console build -n -t v4.1.0 --json api.raml' returned a non-zero code: 130
```
## Allow anonymous usage statistics to help improve our CLI tools?
# Are you seriously?

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.

Usage tracking is nothing unusual even in CLI tools. It will help us organize the options in a way that are most commonly used.

RIght now you can pass `--no-ga` option to skip this question. I may add about 15 seconds timeout to proceed with disabled analytics when no user input.

**Comment by shaburov** [comment]
@jarrodek remove this question for the command `--help`. This will be enough to get to the `--no-ga` flag when building the docker image.
Another good practice is to describe the startup parameters in the `README.md` file.

Thank you for your work.

**Comment by jarrodek** [comment]
I will fix it in the morning (PST), sorry for any inconvenience caused by this.
