### ISSUE TITLE
api-console-cli.log file is created in the current working directory

### ISSUE THREAD

**Issue by eNcacz** [mulesoft-labs/api-console-cli#37]
When i run `api-console -t "RAML 1.0" my-api.raml` then the empty `api-console-cli.log` file is created in the current directory and there is no option to create the file somewhere else (e.g. in `/tmp`) or option disabling creation of this file.

I would like to have a possibility to specify different location of this log file as an optional api-console command line option.

I'm using api-console-cli version 1.0.13

**Comment by jarrodek** [comment]
Hi,
This is good point and I was thinking about changing it somehow so it won't produce this log file.
Also, there must be some issue because the builder should remove this file when there were no errors. I will take a look into this as well.

**Comment by jarrodek** [comment]
This is fixed in 2.0.0
