### ISSUE TITLE
Auth2 popup has not given when serving protected pages

### ISSUE THREAD

**Issue by mserge** [mulesoft-labs/api-console-cli#40]
On windows 10 I'm doing following with raml containing Oauth2 protection (works ok in Anypoint API Exchange). 

- First install tools ```npm install api-console-cli```

- Then in directorywith raml I created build

```npx api-console build -t "RAML 1.0" -a .\salaryapi.raml```

- I can review build files as 
``` npx api-console serve build```

When serving content and using TRY IT:
```
Set this redirect URI in OAuth 2.0 provider settings.

http://127.0.0.1:8081/bower_components/oauth-authorization/oauth-popup.html
```
During the test I have successfull open popup with URL specified as authorizationUri in RAML, but when it returns me back to the redirect url above:http://127.0.0.1:8081/bower_components/oauth-authorization/oauth-popup.html#access_token= 

But the popup shows: 
ENOENT: no such file or directory, stat 'D:\prj\OB\openbanking\salary-api\RAML-proxy\build\bower_components\oauth-authorization\oauth-popup.html'

The directory structure has bower_components\oauth-authorization\oauth-popup.html both under directories:
build/es6-bundle/bower_components/oauth-authorization/oauth-popup.html
build/es5-bundle/bower_components/oauth-authorization/oauth-popup.html

I suppose the polyserve used doesn't support HTML redirection based on bundle version, could you suggest what can be done? Will it affect embedding scenario or using static http service?

**Comment by mserge** [comment]
BTW when I'm using the Anypoint Designer it gives me callback url: 
```Set this redirect URI in OAuth 2.0 provider settings.

https://cdn.anypoint.mulesoft.com/artifacts/api-designer/app/static/js/console-5.2.0.33/es6-bundle/bower_components/oauth-authorization/oauth-popup.html```
And exchange gives:
https://anypoint.mulesoft.com/exchange/api-console/@1.1.28/es6-bundle/bower_components/oauth-authorization/oauth-popup.html

**Comment by mserge** [comment]
https://github.com/mulesoft-labs/api-console-builder/issues/16 @jarrodek  Pavel is that something close to change the root?

**Comment by jarrodek** [comment]
Hi,
I am sorry for lack of response. I never saw the notification.

So, yes, the issue you have referenced was the fix to your problem. Please, let me know if the issue persists.
