### ISSUE TITLE
Update docs - api-console v5 has been released

### ISSUE THREAD

**Issue by madwort** [mulesoft-labs/api-console-cli#41]
Maybe time to update https://github.com/mulesoft-labs/api-console-cli/blob/master/README.md#api-console-cli ? api-console v5 has been released, but please keep the note about which cli version to use for v4 as I just needed to use it!

**Comment by jarrodek** [comment]
I am finishing the release of v6. Because of tight deadlines I'll updated docs with the next release.

**Comment by madwort** [comment]
Cool, thanks!
