### ISSUE TITLE
JSON data elements sequence or position is not pre-served; it is sorted.

### ISSUE THREAD

**Issue by domjok1** [mulesoft-labs/api-console-cli#42]
After the build, the JSON data elements inside the JSON structure are sorted, and does not pre-serve the original sequence or positon.

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report.
Order of what are you referring to? Items in navigation? Examples? There's plenty of items rendered by the console :)

**Comment by domjok1** [comment]
HI,

I am referring to the order of the JSON elements inside the structure. After the build, it sorts the data elements.
Can it not change the order of the data elements in the JSON structure ?


Example:

Before the build, the JSON structure is below:

{
                “orderID”:  12345,
                “warehouse”, “Toronto”
“compCode”: “ABC”,
}

After the build, the data elements in the JSON structure is sorted alphabetically:

{
“compCode”: “ABC”,
                “orderID”:  12345,
                “warehouse”, “Toronto”
}

Thanks

**Comment by jarrodek** [comment]
This is a map. Map has no order. There's nothing I can do. This is how maps work and this is how serialization works. I am not doing it deliberately but there's also nothing I can do to influence that.
